Projet/Projet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
]

Projet/user/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import view_history, dashboard
from user.views import home, logoutUser, register, chefdep, juriste, admin
from user.views import update_user, update_accord, update_partenaire_fdup, update_accordOp, update_avenant, update_avis,  update_contrat, update_convention, update_lettreAccord, update_pds, update_st 
from user.views import  affiche_detail_accord
from user.views import  PasswordsChangeView
from user.views import delete_user, delete_accord, delete_partenaire, delete_fdup, delete_accordOp, delete_avenant, delete_avis,  delete_contrat, delete_convention, delete_lettreAccord, delete_pds, delete_st 
from user.views import accord_create, accordOperation_create, avenant_create, avisJuridique_create, contrat_create, convention_create, lettreAccord_create, pds_create, st_create
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', home, name="home"),
    path('logoutUser', logoutUser, name="logoutUser"),
    path('register', register, name='register'),
    path('chefdep', chefdep, name='chefdep'),
    path('juriste', juriste, name='juriste'),
    path('admin', admin, name='admin'),
    path('dashboard', dashboard, name="dashboard"),
    path('map', views.index, name='dashboard-index'),
    #path affiche
    # path('affiche_accord', affiche_accord, name='affiche_accord'),
    # path('affiche_accordOp', affiche_accordOp, name='affiche_accordOp'),
    # path('affiche_avenant', affiche_avenant, name='affiche_avenant'),
    # path('affiche_avis', affiche_avis, name='affiche_avis'),
    # path('affiche_contrat', affiche_contrat, name='affiche_contrat'),
    # path('affiche_convention', affiche_convention, name='affiche_convention'),
    # path('affiche_lettreAccord', affiche_lettreAccord, name='affiche_lettreAccord'),
    # path('affiche_pds', affiche_pds, name='affiche_pds'),
    # path('affiche_st', affiche_st, name='affiche_st'),
    
    # path create
    path('accord_create', accord_create, name='accord_create'),
    path('accordOperation_create', accordOperation_create, name='accordOperation_create'),
    path('avenant_create', avenant_create, name='avenant_create'),
    path('avisJuridique_create', avisJuridique_create, name='avisJuridique_create'),
    path('contrat_create', contrat_create, name='contrat_create'),
    path('convention_create', convention_create, name='convention_create'),
    path('lettreAccord_create', lettreAccord_create, name='lettreAccord_create'),
    path('pds_create', pds_create, name='pds_create'),
    path('st_create', st_create, name='st_create'),

    # path update
    path('update_partenaire_fdup/<str:c>/', update_partenaire_fdup, name='update_partenaire_fdup'),
    path('update_accord/<str:c>/', update_accord, name='update_accord'),
    path('update_accordOp/<str:c>/', update_accordOp, name='update_accordOp'),
    path('update_avenant/<str:c>/', update_avenant, name='update_avenant'),
    path('update_avis/<str:c>/', update_avis, name='update_avis'),
    path('update_contrat/<str:c>/', update_contrat, name='update_contrat'),
    path('update_convention/<str:c>/', update_convention, name='update_convention'),
    path('update_lettreAccord/<str:c>/', update_lettreAccord, name='update_lettreAccord'),
    path('update_pds/<str:c>/', update_pds, name='update_pds'),
    path('update_st/<str:c>/', update_st, name='update_st'),
    path('update_user/<str:u>/', update_user, name="update_user"),

    # path delete
    path('delete_partenaire/<str:c>/', delete_partenaire, name='delete_partenaire'),
    path('delete_fdup/<str:c>/', delete_fdup, name='delete_fdup'),
    path('delete_accord/<str:c>/', delete_accord, name='delete_accord'),
    path('delete_accordOp/<str:c>/', delete_accordOp, name='delete_accordOp'),
    path('delete_avenant/<str:c>/', delete_avenant, name='delete_avenant'),
    path('delete_avis/<str:c>/', delete_avis, name='delete_avis'),
    path('delete_contrat/<str:c>/', delete_contrat, name='delete_contrat'),
    path('delete_convention/<str:c>/', delete_convention, name='delete_convention'),
    path('delete_lettreAccord/<str:c>/', delete_lettreAccord, name='delete_lettreAccord'),
    path('delete_pds/<str:c>/', delete_pds, name='delete_pds'),
    path('delete_st/<str:c>/', delete_st, name='delete_st'),
    path('delete_user/<str:u>/', delete_user, name="delete_user"),

    #path affiche_detail
    path('affiche_detail_accord/<str:c>/', affiche_detail_accord, name='affiche_detail_accord'),
    
    # history
    path('view_history', view_history, name='view_history'),

    # path('accounts/', include('django.contrib.auth.urls')),
    
    # reset password urls  
    path('password_change',PasswordsChangeView.as_view(template_name='mdp.html'), name="password_change"),
    
    path('password_reset',auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name="password_reset"),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

Projet/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from simple_history.models import HistoricalRecords
import geocoder

# Create your models here.

class User(AbstractUser):
    is_chefdep = models.BooleanField(default=False)
    is_juriste = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    history = HistoricalRecords()

class History(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now=True)
    type = models.CharField(max_length=50)
    prev = models.CharField(max_length=50)
    new = models.CharField(max_length=50)
    field = models.CharField(max_length=50)


class Documents(models.Model):
    nom=models.CharField(max_length=25)
    typee=models.CharField(max_length=25, choices=[
    ('Contrat1', 'Contrat1'),
    ('Contrat2', 'Contrat2'),
    ('Contrat3', 'Contrat3'),
    ('Contrat4', 'Contrat4'),
    ('Contrat5', 'Contrat5'), ])
    document=models.FileField(upload_to='Documents')
    def __str__(self):
        return self.nom


class Contrat(models.Model):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    titre_contrat=models.CharField( max_length=50, unique=True)
    loi=models.CharField(max_length=25, choices=[
    ('86-14', '86-14'),
    ('05-07', '05-07'),
    ('19-13', '19-13'), ])
    date_signature_contrat=models.DateField()
    num_decret=models.IntegerField()
    date_decret=models.DateField()
    date_debut_contrat=models.DateField()
    date_approbation_pod=models.DateField()
    financement_SH=models.FloatField()
    phase_contrat=models.CharField(max_length=25, choices=[
    ('Recherche', 'Recherche'),
    ('Développement', 'Développement'),
    ('Exploitation', 'Exploitation'), ])
    date_fin_contrat=models.DateField()
    date_fin_recherche=models.DateField()
    date_debut_exploitation=models.DateField()
    contrat_pdf=models.FileField(upload_to='Documents/Contrats')
    nom_op=models.CharField(max_length=50, unique=True)
    nom_perimetre=models.CharField(max_length=50, unique=True)
    user = models.CharField(max_length=50, blank=True)
    history = HistoricalRecords()
    
    def __str__(self): 
        return self.code

      
class DocumentContractuel(models.Model):
    titre=models.CharField(max_length=50, unique=True)
    date_de_signature=models.DateField()
    contrat=models.ForeignKey(Contrat, on_delete=models.CASCADE, default=None)
    user = models.CharField(max_length=50, blank=True)
    history=HistoricalRecords(inherit=True)
    class Meta:
        abstract = True 

    def __str__(self):
        return self.code


class AvisJuridique(models.Model):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    titre_avis=models.CharField(max_length=50, unique=True)
    date_avis=models.DateField()
    avis_pdf=models.FileField(upload_to='Documents/Avis_juridiques')
    contrat=models.ForeignKey(Contrat, on_delete=models.CASCADE, default=None)
    user = models.CharField(max_length=50, blank=True)
    history = HistoricalRecords()
    def __str__(self):
        return self.code

# creating a validator function
# def validate_titre_pds(value):
#     for instance in PointDeSituation.objects.all():
#         if instance.titre_pds == value:
#             raise ValidationError(value + ' is already added')
#         else:
#             return value

class PointDeSituation(models.Model):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    titre_pds=models.CharField(max_length=50, unique=True)
    date_pds=models.DateField()
    pds_pdf=models.FileField(upload_to='Documents/Point_de_situations')
    contrat=models.ForeignKey(Contrat, on_delete=models.CASCADE, default=None)
    user = models.CharField(max_length=50, blank=True)
    history = HistoricalRecords()
    def __str__(self):
        return self.code
    

class Partenaire(models.Model):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    nom_partenaire=models.CharField(max_length=50, unique=True)
    pays=models.CharField(max_length=50)
    latitude = models.FloatField(default=0, blank=True)
    longitude = models.FloatField(default=0, blank=True)
    history = HistoricalRecords()
    
    class Meta:
        verbose_name_plural = 'Partenaire'

    def save(self, *args, **kwargs):
        self.latitude = geocoder.osm(self.pays).lat
        self.longitude = geocoder.osm(self.pays).lng
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nom_partenaire

class SoitTransmis(models.Model):
    num_st=models.IntegerField(primary_key=True, default=None)
    id_document=models.CharField(max_length=50, unique=True)
    date_arrivee_st=models.DateField()
    date_depart_st=models.DateField()
    objet=models.CharField(max_length=50)
    expediteur=models.CharField(max_length=50)
    st_pdf=models.FileField(upload_to='Documents/Soit_transmis')
    user = models.CharField(max_length=50, blank=True)
    history = HistoricalRecords()
    def __str__(self):
        return self.id_document

class AccordOperation(DocumentContractuel):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    doc_pdf=models.FileField(upload_to='Documents/Documents_contractuels/Accords_operations')

class Accord(DocumentContractuel):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    doc_pdf=models.FileField(upload_to='Documents/Documents_contractuels/Accords')

class LettreAccord(DocumentContractuel):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    doc_pdf=models.FileField(upload_to='Documents/Documents_contractuels/Lettres_accords')

class Avenant(DocumentContractuel):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    doc_pdf=models.FileField(upload_to='Documents/Documents_contractuels/Avenant')

class ConventionDeDetachement(DocumentContractuel):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    doc_pdf=models.FileField(upload_to='Documents/Documents_contractuels/Conventions')


class FinancementDuPartenaire(models.Model):
    code=models.CharField(primary_key=True, blank=True, max_length=50)
    pourcentage_fin=models.FloatField()
    contrat=models.ForeignKey(Contrat, on_delete=models.CASCADE, default=None)
    partenaire=models.ForeignKey(Partenaire, on_delete=models.CASCADE, default=None)
    history = HistoricalRecords()
    def __str__(self):
        return self.code

Projet/user/forms.py
from django import forms
from .models import Documents
from user.models import Contrat 
from user.models import SoitTransmis
from user.models import PointDeSituation
from user.models import AvisJuridique
from user.models import Partenaire
from user.models import FinancementDuPartenaire
from user.models import AccordOperation
from user.models import Accord
from user.models import LettreAccord
from user.models import Avenant
from user.models import ConventionDeDetachement

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.forms import CharField, IntegerField, DateField


User = get_user_model()

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'password1',
            'password2',
            'email',
            'is_chefdep',
            'is_juriste',
            'is_admin',
        ]

class DocumentsForm(forms.ModelForm):
    class Meta:
       model = Documents
       fields = '__all__'
         
class ContratForm(forms.ModelForm):
   contrath = forms.BooleanField(widget=forms.HiddenInput, initial=True)
   class Meta:
       model = Contrat 
       fields = '__all__'
    #    def clean(self):
    #     cleaned_data = super().clean()
    #     date_signature_contrat = cleaned_data.get("date_signature_contrat")
    #     date_debut_contrat = cleaned_data.get("date_debut_contrat")
    #     date_fin_contrat = cleaned_data.get("date_fin_contrat")
    #     date_fin_recherche = cleaned_data.get("date_fin_recherche")
    #     date_debut_exploitation = cleaned_data.get("date_debut_exploitation")
    #     if date_fin_contrat < date_debut_contrat:
    #         raise forms.ValidationError("Date fin du contrat doit être supérieure à sa date de début.")
    #     if date_fin_recherche < date_debut_contrat:
    #         raise forms.ValidationError("Date fin de la phase de recherche doit être supérieure à la date de début du contrat.")
    #     if date_debut_exploitation < date_debut_contrat:
    #         raise forms.ValidationError("Date début de la phase exploitation doit être supérieure à la date de début du contrat.")
    #     if date_debut_exploitation < date_fin_recherche:
    #         raise forms.ValidationError("Date début de la phase exploitation doit être supérieure à la date de fin de la phase de recherche.")
    #     if  date_debut_contrat < date_signature_contrat :
    #         raise forms.ValidationError("Date début du contrat doit être supérieure à la date de sa signature.")

class SoitTransmisForm(forms.ModelForm):
   class Meta:
       model = SoitTransmis
       fields = '__all__'
       
class PointDeSituationForm(forms.ModelForm):
   class Meta:
       model = PointDeSituation
       fields = ['titre_pds',
       'code',
       'date_pds',
       'pds_pdf', 
       'contrat',
       'user'
       ]
       def clean(self):
        data = self.cleaned_data
        titre = data.get("titre_pds")
        qs = PointDeSituation.objects.filter(titre_pds=titre)
        if qs.exists():
            self.add_error("title", f"\"{titre}\" is already in use. Please pick another title.")
        return data
       
class AvisJuridiqueForm(forms.ModelForm):
   class Meta:
       model = AvisJuridique
       fields = '__all__'
       
     
class PartenaireForm(forms.ModelForm):
    partenaire = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    class Meta:
        model = Partenaire
        fields = '__all__'
    def set_nom_partenaire(self, nom_partenaire):
     data = self.data.copy()
     data['nom_partenaire'] = nom_partenaire
     self.data = data
    def clean_nom_partenaire(self):
      new1=self.cleaned_data['nom_partenaire']
      return new1

       
class FinancementDuPartenaireForm(forms.ModelForm):
   fdup = forms.BooleanField(widget=forms.HiddenInput, initial=True)
   class Meta:
       model = FinancementDuPartenaire
       fields = '__all__'
       
class AccordOperationForm(forms.ModelForm):
   class Meta:
       model = AccordOperation
       fields = '__all__'
       
class AccordForm(forms.ModelForm):
   class Meta:
       model = Accord 
       fields = '__all__'
       
class LettreAccordForm(forms.ModelForm):
   class Meta:
       model = LettreAccord
       fields = '__all__'


class AvenantForm(forms.ModelForm):
   class Meta:
       model = Avenant
       fields = '__all__'  

class ConventionDeDetachementForm(forms.ModelForm):
   class Meta:
       model = ConventionDeDetachement
       fields = '__all__'

class AccordSearchForm(forms.Form):
    num = IntegerField(required=False)
    titre = CharField( max_length=50, required=False)
    date_de_signature = DateField(required=False)

Projet/user/templates/general/base.html
<!DOCTYPE html>
<html  style="background: url('static/images/imag01.jpg') no-repeat center fixed; 
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
background-size: cover; /* version standardisée */"
>
   
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sonatrach</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href={% static 'css/accueil.css' %}>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
  <link rel="icon" type="image/png"  href={% static 'images/logo.png' %}>

  <link rel="stylesheet" href={% static "css/designtable.css" %}>
 <link rel="stylesheet" href={% static "css/table.css" %}>
 <link rel="stylesheet" href={% static 'css/modal.css' %}>
 <link rel="stylesheet" href={% static 'css/register.css' %}>
 <style>
  .de{
    color:#d42a1b; 
    margin-right: 7px;
  }
  .up{
    color: #e49b0f;
    margin-right: 7px;
  }
  .bx{
    font-size:15px;
  }

      button{border:none; background: none;cursor:pointer}
      button{text-decoration: none; color:#353839}
      .sous-header button{
    color:#696969;
    font-weight:550;
    font-size: 13px;
    font-family: arial;
    text-decoration: none;
    }
    .sous-header button :hover{
    color:#ff8c00;
    } 
    h1{font-size: 20px; color:#353839}
    a:hover{color:#ff4f00;}
    .contain{position: relative;top:80px; display:flex; flex-direction: column; gap:30px; justify-content: center; align-items: center;}
    .cont {padding: 15px 20px; background: rgba(255,255,255,0.5) ; border-radius: 5px;}
    .cont a{font-weight: 600; font-size: 17px;}
    center .bx,.cont .fa{font-size: 50px;}
    
.boutton{
        width:100%;
        display: flex;
        justify-content: center;}   
input{height: 40px; position: relative;left:15px}
input:focus{border-color:#1e90ff;}
input[type='submit']
    {margin-bottom: 0;
     width:  150px;
     height: 40px;
     left:0;
     text-align: center;
     padding: 0;
     color:#fff;font-weight: 600;
     background-color:#1e90ff;}
     input[type='submit']:hover{opacity:0.8; transition: opacity 0.1s;}
     .cont h2 {color:#353839}
     .role label {position: relative; top:-12px}
 </style>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>

        <div class="image-text">
          <span class="image">
            <img src={% static 'images/logo-removebg-preview.png' %} alt="">
          </span>
         
         <div class="text header-text">
          <h3><!--Sonatrach--></h3>
         </div>
       
        </div>
      <div class="div2">
         <h1> <i class="fa fa-balance-scale" aria-hidden="true"></i> Gestion des contrats d'associations</h1>
         <span class="nomprenom"><i class='bx bxs-user-circle '></i> {{ request.user.first_name }} {{ request.user.last_name }} <i class='bx bxs-down-arrow ' ></i></span>
        </div>
      </header>
      <ul class="sous-header masquer">
        <li><a href=" {% url "logoutUser" %} "><i class='bx bx-log-out'></i>Deconnexion</li></a>
        <li><a href="{% url "password_change" %}"><i class="fa fa-cog" aria-hidden="true"></i>Paramètres</li></a>
      </ul>
    <center class="contain">

        {% block content %} {% endblock %}
    </center>
   
{% comment %} apres supression et apres modification  {% endcomment %}
{% if messages %}
{% for m in messages %}
<script>
Swal.fire({
icon:'success',
title: 'Félicitations!',
text: "{{m}}",
confirmButtonText: 'OK',
confirmButtonColor:'blue'
})
</script>
{% endfor %}
{% endif%}



{% comment %} class modal update  {% endcomment %}
<div id="demo" class="modal">
<div class="modal_content">
<a href="#" class="modal_close">&times;</a>
<center class="contain">
	<div class="cont" style=" width:350px">
		
		<center>

					<form method="POST" action="#">
						{% csrf_token %}
					<h2> Modifier l'utilisateur " {{x.username}} "</h2>
						{{form.username}}
            {{form.first_name}}
            {{form.last_name}}
            {{form.email}}
            <input type="text" name="password1">
						<input type="text" name="password2"> 
            <div class="role">
							<div class="d1">
							{{form.is_chefdep}}
							<label class="vCheckboxLabel" for="id_is_chefdep">chef de departement</label>
						</div>
						<div class="d2">
							{{form.is_juriste}}
							<label class="vCheckboxLabel" for="id_is_juriste">Juriste</label> 
						</div>
						<div class="d3">
							{{form.is_admin}}
							<label class="vCheckboxLabel" for="id_is_admin">Administrateur</label>
						</div>
            <input type="hidden" name="last_login" value="{{x.last_login}}">
            <input type="hidden" name="is_superuser" value="{{x.is_superuser}}">
            <input type="hidden" name="is_staff" value="{{x.is_staff}}">
            <input type="hidden" name="is_active" value="{{x.is_active}}">
            <input type="hidden" name="date_joined" value="{{x.date_joined}}">
            <input type="hidden" name="id" required value="{{x.id}}">
					</div>
          <div class="boutton"> 
            <input type="submit" value="Valider">
          </div> 
						</form>
					</center>
					
					</div>
          
</div>
</div>
<script>
  /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

//Query All input fields
{% comment %} var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Nom';
form_fields[2].placeholder='Prenom';
form_fields[3].placeholder="Nom d'utilisateur";
form_fields[4].placeholder="Email";
form_fields[5].placeholder='Mot de passe';
form_fields[6].placeholder='Retapez le mot de passe'; {% endcomment %}

</script>

<script>
var td = document.querySelectorAll('td:first-child')
var update = document.querySelectorAll('.update')
var del = document.querySelectorAll('.del')

window.addEventListener("load", function(){
for(var i=0; i<update.length;i++)
{
update[i].href="http://127.0.0.1:8000/update_user/"+ td[i].innerHTML +"/#demo"

del[i].addEventListener("click", function(){
for(var i=0; i<del.length;i++)
{
  var x=td[i].innerHTML
 
  Swal.fire({
    "title":"Êtes-vous sûr?",
    "text":"Vous ne pourrez pas revenir en arrière !",
    "icon":"question",
    "showCancelButton":true,
    "cancelButtonText":"Non, Annuler",
    "confirmButtonText":"Oui, Supprimer",
    "reverseButtons":true,
    "confirmButtonColor":"darkred",
  })
  .then(function(result) {
    if(result.isConfirmed) {
      window.location.href = "http://127.0.0.1:8000/delete_user/"+ x +"/"
    }
  })
}
})
}
})

</script>

</body>
</html>

Projet/user/templates/general/register.html
<!DOCTYPE html>
<html  style="background: url('static/images/imag01.jpg') no-repeat center fixed; 
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
background-size: cover; /* version standardisée */"
>
    
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sonatrach</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href={% static 'css/accueil.css' %}>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
 
  <link rel="icon" type="image/png"  href={% static 'images/logo.png' %}>
  <link rel="stylesheet" href={% static "css/designtable.css" %}>
 <link rel="stylesheet" href={% static "css/table.css" %}>
 <link rel="stylesheet" href={% static "css/register.css" %}>
 
 <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
	<header>

        <div class="image-text">
          <span class="image">
            <img src={% static 'images/logo-removebg-preview.png' %} alt="">
          </span>
         
         <div class="text header-text">
          <h3><!--Sonatrach--></h3>
         </div>
       
        </div>
      <div class="div2">
         <h1> <i class="fa fa-balance-scale" aria-hidden="true"></i> Gestion des contrats d'associations</h1>
		 <span class="nomprenom"><i class='bx bxs-user-circle '></i> {{ request.user.first_name }} {{ request.user.last_name }} <i class='bx bxs-down-arrow ' ></i></span>
        </div>
      </header>
 

	<center class="contain">
	<div class="cont" style=" width:350px">
		<h2> Ajouter un utilisateur</h2>
		<center>

					<form method="POST" action="">
						{% csrf_token %}
					
							<input type="text" name="last_name" required>
						
							<input type="text" name="first_name" required>
						
							<input type="text" name="username" required>
						
							<input type="email" name="email" required>
					
							<input type="text" name="password1">
						
							<input type="text" name="password2"> <br>
						
						<div class="role">
							<div class="d1">
							<input type="checkbox" name="is_chefdep" id="id_is_chefdep">
							<label class="vCheckboxLabel" for="id_is_chefdep">chef de departement</label>
						</div>
						<div class="d2">
							<input type="checkbox" name="is_juriste" id="id_is_juriste" >
							<label class="vCheckboxLabel" for="id_is_juriste">Juriste</label> 
						</div>
						<div class="d3">
							<input type="checkbox" name="is_admin" id="id_is_admin">
							<label class="vCheckboxLabel" for="id_is_admin">Administrateur</label>
						</div>
					</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn"  type="submit" value="Register Account" >
							 </div>
						</form>
					</center>
					
					</div>
					
					<div class="cont"style=" position:fixed; top:90%; left:5%; font-weight: 600">  
					<a href="{% url 'admin' %}" >
					Retour à la page d'accueil </a>
					</div>
				</center>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nom';
		form_fields[2].placeholder="Prénom";
		form_fields[3].placeholder="Nom d'utilisateur";
		form_fields[4].placeholder="Email";
		form_fields[5].placeholder='Mot de passe';
		form_fields[6].placeholder='Retapez le mot de passe';

	</script>
  {% comment %} apres supression et apres modification  {% endcomment %}
  {% if messages %}
  {% for m in messages %}
  <script>
   Swal.fire({
	icon:'success',
	title: 'Félicitations!',
	text: "{{m}}",
	confirmButtonText: 'OK',
	confirmButtonColor:'blue'
  })
  </script>
  {% endfor %}
  {% endif%}
	

</body>
</html>









